### ISSUE TITLE
Standardize README

### ISSUE THREAD

**Issue by weddleben** [waifuvault/waifuVault-node-api#1]
Do you want me to go through and adjust the README files for the other library repos so they match the [changes we made](https://github.com/waifuvault/waifuVault-python-api/pull/2) in the Python repo? I think it would look better if they were all the same, and I think the anchor links/tags would be beneficial for the webpages on both NPM & NuGet.

I don't mind doing it, but want to check with you before I start.

**Comment by VictoriqueMoe** [comment]
> Do you want me to go through and adjust the README files for the other library repos so they match the [changes we made](https://github.com/waifuvault/waifuVault-python-api/pull/2) in the Python repo? I think it would look better if they were all the same, and I think the anchor links/tags would be beneficial for the webpages on both NPM & NuGet.
> 
> I don't mind doing it, but want to check with you before I start.

sound good, i will add you as an outside contributor

**Comment by weddleben** [comment]
Thank you, Victoria! I'll get started on these changes soon.

**Comment by weddleben** [comment]
closing per 37d41fd
