### ISSUE TITLE
return value of deleteFile

### ISSUE THREAD

**Issue by weddleben** [waifuvault/waifuVault-node-api#5]
Per the [documentation](https://github.com/waifuvault/waifuVault-node-api?tab=readme-ov-file#delete-file), the `deleteFile` function returns either true or false. But per the [code](https://github.com/waifuvault/waifuVault-node-api/blob/main/src/WaifuApi.ts#L132), an exception is thrown if an invalid token is passed to the function. 

Should the `checkError` function be handled differently? Or should the documentation be updated?

I just ran into this with @nakedmcse's  [Python implementation](https://github.com/waifuvault/waifuVault-python-api/), which also throws an exception when an invalid token is passed. But I thought I'd mention here first, since this SDK was written first.

**Comment by VictoriqueMoe** [comment]
> Per the [documentation](https://github.com/waifuvault/waifuVault-node-api?tab=readme-ov-file#delete-file), the `deleteFile` function returns either true or false. But per the [code](https://github.com/waifuvault/waifuVault-node-api/blob/main/src/WaifuApi.ts#L132), an exception is thrown if an invalid token is passed to the function.
> 
> Should the `checkError` function be handled differently? Or should the documentation be updated?
> 
> I just ran into this with @nakedmcse's [Python implementation](https://github.com/waifuvault/waifuVault-python-api/), which also throws an exception when an invalid token is passed. But I thought I'd mention here first, since this SDK was written first.

Yes, this is correct. the delete endpoint can only ever either either return `true` or throw an exception. 

The node API should really return `<true | never>` for the response of `delete` as this better conforms to the API.

**Comment by VictoriqueMoe** [comment]
I also think it should be documented that the delete endpoint will throw an exception if the token is invalid instead of returning `false` to make people aware that they will need to use a try catch rather than a boolean check. good point

**Comment by weddleben** [comment]
> I also think it should be documented that the delete endpoint will throw an exception if the token is invalid instead of returning `false` to make people aware that they will need to use a try catch rather than a boolean check. good point

Agreed! Happy to take a stab at updating the documentation if you'd like.

**Comment by VictoriqueMoe** [comment]
sure, do you also want to update the code too to return `<true | never>` ?

**Comment by weddleben** [comment]
I do not speak TS and can't test it properly. I don't even know whether it's `deleteFile` or `checkError` that needs to be changed.

EDIT: OK, looks like it's `deleteFile` that needs its return type updated. got it, I think. Still, probably best if you do it.

**Comment by VictoriqueMoe** [comment]
> I do not speak TS and can't test it properly. I don't even know whether it's `deleteFile` or `checkError` that needs to be changed.
> 
> EDIT: OK, looks like it's `deleteFile` that needs its return type updated. got it, I think. Still, probably best if you do it.

Okay, i will update it and make the readme change too. thanks

**Comment by weddleben** [comment]
you are welcome :) I'll create an issue in the Python SDK as well

**Comment by VictoriqueMoe** [comment]
I think the Python and GO ones will be just documentation, so if you want to edit the readme for those, it will be enough, i am not sure if C# allowes you to define a `throws`  @nakedmcse will be able to say

**Comment by weddleben** [comment]
> I think the Python and GO ones will be just documentation, so if you want to edit the readme for those, it will be enough...

yes, he doesn't have return type hints currently, so just documentation. [Issue opened](https://github.com/waifuvault/waifuVault-python-api/issues/5)

**Comment by VictoriqueMoe** [comment]
> > I think the Python and GO ones will be just documentation, so if you want to edit the readme for those, it will be enough...
> 
> yes, he doesn't have return type hints currently, so just documentation. [Issue opened](https://github.com/waifuvault/waifuVault-python-api/issues/5)

Please see https://github.com/waifuvault/waifuVault-node-api/pull/6
